version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
    ports:
      - "${ES_PORT}:9200"
    networks: ['stack']

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    ports:
      - "5044:5044"
    volumes:
      - ./config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    ports:
      - "${KIBANA_PORT}:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks: ['stack']

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
    command: [ "-c", "/usr/share/metricbeat/metricbeat.yml", "-e" ]
    volumes:
      - "./config/metricbeat/metricbeat.yml:/usr/bin/metricbeat/metricbeat.yml:ro"
    networks: ['stack']

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${STACK_VERSION}
    command: [ "-c", "/usr/share/heartbeat/heartbeat.yml", "-e", "-strict.perms=false" ]
    volumes:
      - "./config/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro"
    networks: ['stack']

networks:
  stack: {}