spring:
  application:
    name: spring-boot-elk

logging:
  config: classpath:logback-spring.xml


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always